// Every English sentence on the page. FR-105.
//
// Typed against `ko.ts`, which defines the shape: a label added there and not
// here fails the build rather than showing a Korean sentence to an English
// reader.

import type { Progress } from '../api'
import type { Codes, Labels, Stages } from './ko'

export const L: Labels = {
  title: 'Multiband Hall analysis',
  lede: 'From rho_xx(B) and rho_xy(B): first how many carriers the data determines, then their densities and mobilities.',

  language_label: 'Language',
  language_ko: '한국어',
  language_en: 'English',

  step_files: '1. Files',
  step_mapping: '2. Columns',
  step_settings: '3. Procedure',
  step_run: '4. Analysis',
  step_results: '5. Results',
  step_adjust: '6. Adjust and confirm',
  // FR-112. The procedure's answer stays in step 5; the adjusting happens here.
  adjust_heading: '6. Adjusting after the fact, and confirming',
  adjust_lede: 'For when the procedure landed somewhere unphysical at one temperature, or the series cannot be read as one series. Nothing here erases the answer in step 5.',
  adjust_back: 'Back to 5. Results',
  adjust_moved: 'Refitting at a different band count, and coupling across temperature, have moved to step 6. There you can work through several temperatures in turn and, when satisfied, confirm and download.',
  adjust_go: 'Go to 6. Adjust and confirm',
  adjust_pick: 'Choose a temperature to work on',
  adjust_working: 'Adjustments so far',
  adjust_nothing: 'Nothing adjusted yet. Every temperature you do not touch keeps the answer the procedure reached.',
  adjust_now: 'Standing now',
  adjust_source: 'From',
  adjust_undo: 'Undo',
  confirm_heading: 'Confirm',
  confirm_intro: 'Confirming does not gather the numbers on this screen. It runs the procedure again, under the settings your adjustments amount to, so it takes minutes. What that buys is that the tables you download describe one run throughout, and that the configuration document included with them gives the same answer on the command line.',
  confirm_settings: (counts: number, bands: number) =>
    `Pins the count at ${counts} temperatures and couples ${bands} band(s).`,
  confirm_run: 'Confirm and run again',
  confirm_running: 'Running again under the confirmed settings...',
  confirm_stopped: 'Stopped. An answer confirmed for only some temperatures is not a confirmed answer, so nothing was kept.',
  confirm_done: 'Confirmed. The files below are this confirmed answer; the answer the procedure reached is still downloadable from step 5.',
  confirm_download_tables: 'Tables and the document (.zip)',

  offline_heading: 'The program is not answering',
  offline_body: (address: string) =>
    `This window is holding ${address}, and nothing is answering there. Either the program is not running, or this window belongs to a run that is over.`,
  offline_what: 'Start MultibandHall.exe. This window comes back by itself once it does. If it does not, use the window that opens with it.',
  offline_lost: 'Files uploaded before will not survive the restart. You will upload them again.',
  offline_retry: 'Check again now',
  offline_checking: 'Checking…',

  col_island: 'Count both neighbours share (island)',
  island_cell: (label: string, times: string) => `${label}, residual ${times}x`,
  island_intro: 'The "island" column marks a temperature carrying more carriers than a count both of its neighbours share. The factor beside it is what the residual becomes when this temperature is held to their count. The verdict was not changed — whether it is a real transition or something the fit made is yours to judge. To hold it, use "Refit at a different band count" below.',

  recount_heading: 'Refit at a different band count',
  recount_intro: 'Refits at a count you choose instead of the one the procedure picked. The whole analysis is not run again, only the temperatures you select. Choosing a band holds every sweep in it to the same count, which is what lets n(T) and mu(T) be drawn from one carrier set. The original verdict stays, and what the change cost appears as a residual factor. A factor below 1 means your count fits better; why the procedure did not take it is in the gates of the candidate table below.',
  recount_holes: 'holes',
  recount_electrons: 'electrons',
  recount_from: 'from',
  recount_to: 'to',
  recount_chosen: (n: number) => `Applies to ${n} temperature${n === 1 ? '' : 's'}.`,
  recount_run: 'Refit',
  recount_running: 'Refitting…',
  recount_original: 'Procedure',
  // FR-109. The refit reaches the plots and the tables, beside the procedure.
  recount_shown: 'The plots and the carrier table above now show this beside the answer the procedure reached.',
  recount_clear: 'Remove from the plots',
  refit_showing: (what: string, where: string) =>
    `Showing a refit (${what}, ${where}) beside the answer the procedure reached. That answer is not replaced.`,
  trend_procedure: 'procedure',
  trend_refit: 'refit',
  trend_coupled: 'coupled',
  trend_adjusted: 'adjusted',
  col_source: 'From',
  recount_result: 'Refitted',
  recount_col_price: 'Residual factor',

  spectrum_show: 'Show the mobility spectrum (MSA)',
  spectrum_intro: 'The mobility spectrum computed in step 1. The bound on the band count and the mobility ranges came from it. The vertical axis is the normalised weight the spectrum solves for, not a carrier density — it is the fraction of the conduction a peak carries. Look at whether the peaks stand apart or sit as shoulders of one another: where they merge, the two cannot be told apart.',
  spectrum_hole: 'hole',
  spectrum_electron: 'electron',
  spectrum_peak_hole: 'hole peaks',
  spectrum_peak_electron: 'electron peaks',
  spectrum_x: 'Mobility (cm^2/Vs)',
  spectrum_y: 'Weight (normalised)',
  spectrum_title: (T: number) => `Mobility spectrum at ${T} K`,
  spectrum_window: (kind: string, low: string, high: string) =>
    `${kind} search window: ${low} to ${high} cm^2/Vs`,
  spectrum_none: 'There is no spectrum for this temperature.',

  smooth_heading: 'Smooth across temperature',
  smooth_intro: 'The band can be solved as one problem, with a constraint that the parameters vary smoothly with temperature. It is not free — smoothness is bought with residual, and what each temperature paid is shown. A large price is evidence that the model really does change across the band: read it as a reason to divide the band, not to press harder.',
  smooth_label: 'Smoothing',
  smooth_none: 'none',
  smooth_weak: 'weak',
  smooth_normal: 'normal',
  smooth_strong: 'strong',
  smooth_needs: 'Three temperatures or more. A curvature needs three points.',
  smooth_col: 'Smoothed',
  smooth_run: 'Couple across temperature',
  smooth_running: 'Fitting the band as one problem...',
  smooth_stopped: 'Stopped. A band half coupled is not a smooth series, so the coupling keeps nothing. The refit it was asked of is untouched.',
  smooth_ask: (n: number) => `A coupling can be asked of the ${n} temperatures just refitted.`,
  smooth_elapsed: (seconds: string, budget: string) =>
    `${seconds} s elapsed, of a budget of ${budget} s. The whole band is one calculation, so there is nothing to count temperature by temperature.`,
  smooth_long_band: (n: number) =>
    `${n} temperatures is a long band. A coupling grows sharply more expensive with the length of the band - eight temperatures take minutes, thirteen take far longer. Dividing it is faster, and usually reads better too.`,
  recount_stopped: 'Stopped. A band held to one count for half its temperatures is not a series either, so nothing was kept.',
  recount_unheld: (list: string) => `The count would not fit at: ${list}. No starting point finished inside the budget there. The procedure's own answer still stands at those sweeps, and they are not entered in the adjustments below.`,
  roughness_label: 'Roughness of the band',
  roughness_none: 'Measurable only on a band of three or more temperatures that share a count.',
  roughness_note: (value: string) =>
    `The roughness of this band is ${value}. It is how far the parameters bend with temperature, measured as the quantity the constraint would act on. Smaller is easier to read as one series.`,
  smooth_done: (strength: string, before: string, after: string) =>
    `Smoothed at ${strength}. Roughness ${before} to ${after}. What each temperature paid is in the right-hand column.`,

  files_heading: 'Upload the measurements',
  files_intro: 'One file per temperature or many temperatures in one file, either way. Files do not leave this computer.',
  files_drop: 'Drop files anywhere on this page, or click here to choose them',
  files_formats: 'CSV, TXT, DAT (comma, semicolon, tab or space separated; decimal comma; UTF-8, CP949, UTF-16). rho_xx and rho_xy in separate files is fine. Save Excel files (.xlsx) as CSV first.',
  files_pick_folder: 'Choose a folder',
  files_skipped: (n: number) => `${n} file${n === 1 ? '' : 's'} skipped: not a table (CSV, TXT, DAT).`,
  files_temperatures: (ts: number[]) =>
    ts.length <= 4 ? ts.map((t) => `${t} K`).join(', ') : `${ts[0]}–${ts[ts.length - 1]} K, ${ts.length} temperatures`,
  files_conflict: (one: string, others: string[], temps: string[]) =>
    `${one} and ${others.length > 3 ? `${others.slice(0, 3).join(', ')} and ${others.length - 3} more` : others.join(', ')} hold the same measurement at the same temperature${temps.length === 1 ? '' : 's'} (${temps.length > 4 ? `${temps[0]}–${temps[temps.length - 1]}` : temps.join(', ')}). If the same data was uploaded twice, keep one.`,
  files_remove_one: (name: string) => `Remove ${name}`,
  files_remove_others: (n: number) => `Remove the other ${n}`,
  files_conflict_block: 'The overlap has to be settled before the next step.',
  files_uploading: 'Reading…',
  files_listed: 'Uploaded',
  files_remove: 'Remove',
  files_next: 'To columns',

  mapping_heading: 'Columns of each file',
  mapping_intro: 'What the program guessed. Confirm it, and correct it where it is wrong. Nothing is analysed until every file is fully specified.',
  mapping_skipped: (n: number) => (n > 0 ? `${n} line${n === 1 ? '' : 's'} above the header skipped.` : 'No lines skipped'),
  mapping_rows: (shown: number, total: number) => `first ${shown} of ${total} rows`,
  mapping_B: 'Field column',
  mapping_rhoxx: 'rho_xx column',
  mapping_rhoxy: 'rho_xy column',
  mapping_T_source: 'Temperature',
  mapping_T_from_column: 'from a column',
  mapping_T_value: 'typed in (K)',
  mapping_T_column: 'Temperature column',
  mapping_field_unit: 'Field unit',
  mapping_resistivity_unit: 'Resistivity unit',
  mapping_choose: '— choose —',
  mapping_missing: (what: string) => `Not specified yet: ${what}`,
  mapping_T_from_name: (T: number) => `Read ${T} K from the file name.`,
  mapping_back: 'To files',
  mapping_next: 'To the procedure',

  settings_heading: 'The procedure',
  settings_intro: 'Every temperature of every file is analysed in this order.',
  procedure_steps: [
    'A mobility spectrum (MSA) sets the bound on the band count for holes and for electrons, and the ranges of carrier density and mobility.',
    'Inside those ranges, combinations are fitted with the multiband Drude model, and the smallest is chosen that describes the data and gives the same answer from different starting points.',
    'If one more band cuts the residual decisively — by more than a factor of 2 — the count grows; otherwise it is settled there. Adding a carrier always lowers the residual a little, so an improvement of that size is no reason to add one.',
  ],
  procedure_claim: 'The band count in the answer is a lower bound on the conduction channels this data requires, and the densities and mobilities are effective values of those channels. There may be more Fermi pockets than that, and showing it needs evidence from outside magnetotransport, such as quantum oscillations.',
  sym_heading: 'Symmetrising the data',
  sym_intro: 'Turns the measurement into its even and odd parts. Off, so that the program does not change your data without being asked. The parity violation is measured before any change.',
  sym_rhoxx: 'Symmetrise rho_xx in B (even part)',
  sym_rhoxy: 'Antisymmetrise rho_xy in B (odd part)',
  prelim_heading: 'The preliminary model',
  prelim_intro: 'The spectrum takes its noise level from the residual of a preliminary fit. Unless you supply one, a generic model is used: two holes and two electrons, starting at 10^4 and 10^3 cm^2/Vs. This model only measures the noise level and is not the answer — the final carrier count and mobilities are found again inside the bound the spectrum gives, so a starting model that does not suit your sample does not pull the answer towards itself. Compared against the carefully seeded model on this project’s twelve sweeps, it gave the same carrier bound at every temperature and the same noise level to within 3 %.',
  prelim_document: 'Use a configuration document (JSON) instead',
  prelim_document_hint: 'Paste a configuration document with the carrier declarations and workflow settings (fixed_counts, for instance). The program fills in the column names.',
  prelim_document_invalid: 'The configuration document is not valid JSON.',
  settings_back: 'To columns',
  settings_start: 'Start the analysis',

  run_heading: 'Analysing',
  run_stop: 'Stop',
  run_stopping: 'Stopping… the fit now running has to finish first (about 30 seconds at most).',
  run_elapsed: (s: number) => `${Math.round(s)} s elapsed`,

  results_heading: 'Results',
  results_stopped: 'The analysis was stopped. Only the temperatures finished before that are shown.',
  results_dropped: (n: number) => `${n} row${n === 1 ? '' : 's'} dropped from the uploads before the fit: the temperature or the field could not be read. A whole sweep can go this way, so check the column mapping and the files.`,
  results_failed: 'The analysis failed.',
  results_new: 'New analysis',
  results_download_page: 'Download the report (report.html)',
  results_download_tables: 'Download the tables (tables.zip)',
  results_seconds: (s: number) => `took ${Math.round(s)} s`,
  results_prelim: (list: string) => `Preliminary model: ${list}`,
  count_notice_peaks_cli: 'The count was held to the spectrum’s peaks (command line --count peaks). Quote this only where evidence from outside magnetotransport supports the count.',
  count_notice_data: 'Count rule: decided by the data. The carrier count is a lower bound on the conduction channels this sweep requires, and the values are the effective densities and mobilities of those channels. There may be more pockets.',

  verdict_heading: '1. Verdict per temperature',
  verdict_intro: 'Read this before the numbers. Clicking a row moves everything below to that temperature.',
  curves_heading: '2. Measurement and model',
  params_heading: '3. Carriers',
  trends_heading: '4. Parameters against temperature',
  trends_intro: 'The vertical axis is logarithmic. Where the combination differs from temperature to temperature this is not a series — to hold the count, use fixed_counts in a configuration document.',
  cands_heading: '5. Every combination tried',
  cands_none: 'This mode does not search combinations.',

  col_T: 'T (K)', col_combo: 'Combination', col_grade: 'Grade', col_r2xx: 'R^2 rho_xx', col_r2xy: 'R^2 rho_xy',
  col_cond: 'Condition', col_failed: 'Gates failed', col_escaped: 'Left the window', col_stop: 'Loop stop',
  col_undetermined: 'Undetermined fit that fits better',
  col_fit_ratio: 'Residual/noise rho_xx / rho_xy',
  beyond_mark: '(past the MSA bound)',
  undetermined: (label: string, ratio: string) => `${label}: residual ${ratio}x smaller, does not reproduce`,
  col_name: 'carrier', col_kind: 'kind', col_density: 'Density (cm^-3)', col_mobility: 'Mobility (cm^2/Vs)',
  col_share: 'Conduction share', col_weakest: 'Weakest share', col_holes: 'holes', col_electrons: 'electrons', col_rmse: 'RMSE rho_xx',
  col_spread: 'Spread', col_bound: 'On a bound', col_expired: 'Over budget',
  col_starts: 'Starts finished', col_seconds: 's',
  col_quantity: 'Quantity', col_value: 'Value', col_low: 'Low', col_high: 'High', col_relative: 'Relative 1 sigma',

  grade: { A: 'A: the parameters are determined', B: 'B: trends usable, digits not', C: 'C: shape only', D: 'D: undetermined', '-': 'no answer' } as Record<string, string>,
  gate: { fits: 'does not fit', reproducible: 'does not reproduce', earns: 'a carrier doing no work', free: 'resting on a bound' } as Record<string, string>,
  stop: { converged: 'converged', max_iterations: 'iteration limit', fit_out_of_budget: 'fit out of budget', no_peaks: 'no peaks' } as Record<string, string>,
  no_answer: 'No answer: no peaks, or no fit finished inside the budget',
  none: 'none', yes: 'yes', no: 'no',
  hole: 'hole', electron: 'electron',
  rhoxx: 'rho_xx (uOhm cm)', rhoxy: 'rho_xy (uOhm cm)', field: 'B (T)', temperature: 'T (K)',
  density: 'Density (cm^-3)', mobility: 'Mobility (cm^2/Vs)',
  measured: 'measured', model: 'model',
  no_curve: 'There is no curve to draw.',

  precise_heading: 'Precise check (resampling)',
  precise_intro: 'Resamples the residual at one temperature to give intervals for the densities and mobilities. It takes minutes.',
  precise_start: (T: number) => `Check ${T} K precisely`,
  precise_running: (done: number, total: number) => `resample ${done} / ${total}`,
  precise_stopped: 'The precise check was stopped. An interval from part of the resamples is a different interval, so nothing was kept.',
  precise_result: (n: number, block: number, seed: number) => `${n} resamples, block length ${block}, seed ${seed}`,
  precise_lower_bound: 'The residual at this temperature is structured. The intervals below are lower bounds.',

  notice_interval: 'The grade, the spread and the resampling intervals are reproducibility within the model. Model error is not in them.',
  notice_mobility: 'An extracted mobility is the effective mobility of that conduction channel, and is not the microscopic mobility of any one Fermi pocket.',
  notice_peaks: 'A peak in the spectrum is a conduction channel, not a band. The number of peaks is a bound on the number of bands, not an estimate of it.',
}

export const STAGES: Stages = {
  prepare: (p: Progress) => `Reading the data and fitting the preliminary model (${p.total ?? '?'} temperatures)`,
  spectrum: (_p: Progress, T: string) => `${T}: computing the mobility spectrum`,
  temperature: (_p: Progress, T: string) => `${T}: starting`,
  search: (p: Progress, T: string, combo: string) =>
    `${T}: fitting ${combo} (bound ${p.max_holes ?? '?'}h+${p.max_electrons ?? '?'}e)`,
  release: (_p: Progress, T: string, combo: string) => `${T}: refitting the chosen ${combo} without the window`,
  peaks: (p: Progress, T: string, combo: string) =>
    `${T}: fitting ${combo} at the peak count, pass ${p.iteration ?? ''}`,
  fixed: (_p: Progress, T: string, combo: string) => `${T}: fitting at the pinned count ${combo}`,
  smooth: (_p: Progress, T: string) => `${T ? `${T}: ` : ''}fitting the band together`,
  resample: (p: Progress, T: string) => `${T}: resample ${p.done ?? 0} / ${p.total ?? '?'}`,
  done: () => 'Finishing',
}

export const STAGE_DEFAULT = 'Starting'

export const CODE_MESSAGES: Record<Codes, string> = {
  E_UPLOAD_EMPTY: 'No file was uploaded, or the file is empty.',
  E_UPLOAD_UNREADABLE: '{file}: cannot be read as a separated text table.',
  E_UPLOAD_NO_TABLE: '{file}: no run of numeric rows was found. Check that it is a text table with the field and the resistivities in columns.',
  E_UPLOAD_SPREADSHEET: '{file}: Excel files cannot be read directly. Save as "CSV (comma delimited)" from Excel and upload that.',
  E_FILE_UNKNOWN: 'The server no longer holds this file. Upload it again.',
  E_MAPPING_INCOMPLETE: '{file}: something is not specified ({missing}). If rho_xx and rho_xy come from different files, upload the matching file for the same temperature as well.',
  E_MAPPING_UNKNOWN_COLUMN: '{file}: there is no column "{column}" in the file.',
  E_MAPPING_BAD_UNIT: '{file}: unknown unit {unit}.',
  E_TEMPERATURE_DUPLICATE: '{T_K} K is in two files: {files}. Nothing is merged or overwritten. Remove one of them.',
  E_COUNT_RULE_UNKNOWN: 'Unknown count rule {count}.',
  E_PRECISE_NO_ANSWER: 'There is no fit to resample at {T_K} K.',
  E_JOB_NOT_FOUND: 'This job cannot be found. Jobs do not survive restarting the program.',
  E_JOB_NOT_FINISHED: 'Only after the analysis has finished.',
  E_PRECISE_UNKNOWN_TEMPERATURE: '{T_K} K is not in this analysis.',
  E_RECOUNT_INVALID: 'The carrier count is not usable. Holes and electrons together must be at least 1 and at most {most}.',
  E_SMOOTHING_TOO_FEW: '{given} temperatures cannot be smoothed. A curvature needs at least {needed} temperatures in the band.',
  E_SMOOTHING_UNKNOWN: 'That smoothing strength does not exist ({smooth}).',
  E_SMOOTH_NO_BAND: 'A coupling is asked of a refit that has already finished. Refit the band at your chosen count first.',
  E_BAND_COUNTS_DIFFER: 'The sweeps in this band do not share one carrier count ({counts}). There is nothing to couple; refit the whole band at one count first.',
  E_BUDGET_EXPIRED: 'The coupled fit did not finish within its budget of {seconds} s and was abandoned. Divide the band or take a shorter one - a longer band is sharply more expensive.',
  E_CONFIRM_EMPTY: 'There is no adjustment to confirm. Refit something first.',
  E_REQUEST_INVALID: 'The request has the wrong shape ({fields}).',
  E_INTERNAL: 'Something unforeseen went wrong: {detail}',
  E_NOT_FOUND: 'Not found.',
  E_NETWORK: 'The program could not be reached. Either it is not running, or this window belongs to a run that is over. Starting MultibandHall.exe brings this window back by itself.',

  E_CONFIG_UNREADABLE: 'The configuration document cannot be read.',
  E_CONFIG_SCHEMA_VERSION: 'The configuration document has no schema_version, or one that is not supported.',
  E_CONFIG_UNKNOWN_FIELD: 'The configuration document has a field the program does not know ({field}). It is refused rather than ignored, so that a misspelling cannot quietly leave a default in force.',
  E_CONFIG_MISSING_FIELD: 'The configuration document is missing a required field ({field}).',
  E_CONFIG_BAD_VALUE: 'A configuration value is outside what is allowed ({field}).',
  E_CONFIG_NO_CARRIERS: 'The configuration document must declare at least one carrier.',
  E_CONFIG_DUPLICATE_CARRIER: 'Two carriers have the same name.',
  E_CONFIG_BAD_CARRIER_KIND: 'A carrier’s kind must be electron or hole.',
  E_CONFIG_BOUNDS_INVALID: 'The bounds are not usable: min must be above zero and at most max.',
  E_CONFIG_INIT_OUT_OF_BOUNDS: 'An initial value is outside its bounds.',
  E_CONFIG_UNKNOWN_CARRIER: 'A carrier name was referred to that was never declared.',
  E_CONFIG_EMPTY_FIELD_WINDOW: 'The field window leaves no records at some temperature.',
  E_CONFIG_COUPLING_WITHOUT_GLOBAL: 'A coupling penalty or a monotonic prior acts only when temperature_strategy is global_smooth.',
  E_CONFIG_BREAK_OUTSIDE_RANGE: 'A smoothing break is outside the measured temperature range.',
  E_DATA_UNREADABLE: 'The combined data cannot be read.',
  E_DATA_MISSING_COLUMN: 'The data is missing a required column.',
  E_DATA_EMPTY: 'No usable record is left. Check the column mapping and the units.',
  E_DATA_UNDERDETERMINED: 'Some temperature has fewer data points than free parameters.',
  E_FIT_NO_START: 'Every starting point failed.',
  E_FIT_SINGULAR: 'The conductivity tensor cannot be inverted (sigma_xx^2 + sigma_xy^2 = 0).',
}

export const UNKNOWN_CODE = (code: string) => `Unknown error (${code})`
